package annotations.computed_column

/**
 * Annotation to define a computed column in a database table.
 * The `compute` parameter allows specifying a JavaScript expression that computes the value of the column.
 * The expression can only use JavaScript code to reference and transform other column values.
 * The `readOnly` parameter indicates whether the column is read-only or can be manually updated.
 *
 * Example usage:
 * ```
 * val name = varchar("name", 150)
 *
 * @ComputedColumn(
 *     compute = "{name}.toLowerCase().replaceAll(' ', '-')"
 *     readOnly = true
 * )
 * val slug = varchar("slug", 500)
 * ```
 * In this example, the `slug` column is automatically generated by converting the `name` column to lowercase
 * and replacing spaces with dashes, using JavaScript code.
 */
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.PROPERTY)
annotation class ComputedColumn(
    val compute: String,
    val readOnly: Boolean = true
)